/**
 * pdfReportGenerator.js
 * Generates a structured PDF using pdfmake matching the old backend report.html style
 */

import pdfMake from "pdfmake/build/pdfmake";
import * as pdfFonts from "pdfmake/build/vfs_fonts";

// Initialize vfs logic to handle Vite bundle issues securely
if (pdfFonts && pdfFonts.pdfMake) {
  pdfMake.vfs = pdfFonts.pdfMake.vfs;
} else if (pdfFonts && pdfFonts.vfs) {
  pdfMake.vfs = pdfFonts.vfs;
} else if (window.pdfMake) {
  pdfMake.vfs = window.pdfMake.vfs;
}

export function generateStructuredPDF(data) {
  // ── 1. Top Analyzed Topics Table ───────────────────────────────────────
  const topicsBody = [
    [
      { text: 'Rank', style: 'tableHeader' },
      { text: 'Topic', style: 'tableHeader' },
      { text: 'Module', style: 'tableHeader' },
      { text: 'Frequency', style: 'tableHeader' }
    ]
  ];

  const topTopics = (data.ranked_topics_overall || []).slice(0, 15);
  topTopics.forEach((topic, idx) => {
    topicsBody.push([
      (idx + 1).toString(),
      { text: topic.topic, bold: true },
      `Module ${topic.module}`,
      topic.raw_count.toString()
    ]);
  });

  // ── 2. Predictions List ────────────────────────────────────────────────
  const predictionsArray = [];
  const topPreds = (data.top_predictions_overall || []).slice(0, 10);
  topPreds.forEach(pred => {
    predictionsArray.push({
      text: [
        { text: `${pred.topic}`, bold: true },
        { text: ` (Module ${pred.module})\n`, color: '#4a5568' },
        { text: `Prediction Confidence: ${pred.confidence_pct}%`, fontSize: 10, color: '#718096' }
      ],
      margin: [0, 5, 0, 5]
    });
  });

  // ── 3. Module Tables (Part A & B) ──────────────────────────────────────
  const moduleBlocks = [];

  for (let mod = 1; mod <= 5; mod++) {
    const block = data.module_structure[String(mod)];
    if (!block || (!block.partA.length && !block.partB.length)) continue;

    moduleBlocks.push({ text: `Module ${mod}`, style: 'subheader', margin: [0, 15, 0, 5] });

    // Part A table
    if (block.partA.length > 0) {
      moduleBlocks.push({ text: 'Part A', style: 'partHeader', margin: [0, 5, 0, 3] });
      const partABody = [
        [
          { text: 'Q No.', style: 'tableHeader', width: 'auto' },
          { text: 'Question', style: 'tableHeader', width: '*' },
          { text: 'Source', style: 'tableHeader', width: 'auto' }
        ]
      ];
      block.partA.forEach(q => {
        partABody.push([
          q.number.toString(),
          q.text,
          { text: q.source.replace('.pdf', ''), fontSize: 9 }
        ]);
      });
      moduleBlocks.push({
        table: {
          headerRows: 1,
          widths: ['auto', '*', 'auto'],
          body: partABody
        },
        layout: 'lightHorizontalLines',
        margin: [0, 0, 0, 10]
      });
    }

    // Part B table
    if (block.partB.length > 0) {
      moduleBlocks.push({ text: 'Part B', style: 'partHeader', margin: [0, 5, 0, 3] });
      const partBBody = [
        [
          { text: 'Q No.', style: 'tableHeader', width: 'auto' },
          { text: 'Sub', style: 'tableHeader', width: 'auto' },
          { text: 'Question', style: 'tableHeader', width: '*' },
          { text: 'Source', style: 'tableHeader', width: 'auto' }
        ]
      ];
      block.partB.forEach(q => {
        const subs = q.subQuestions || [];
        subs.forEach(sub => {
          partBBody.push([
            q.number.toString() + (q.is_or_variant ? ' (OR)' : ''),
            sub.marker || '-',
            sub.text,
            { text: q.source.replace('.pdf', ''), fontSize: 9 }
          ]);
        });
      });
      moduleBlocks.push({
        table: {
          headerRows: 1,
          widths: ['auto', 'auto', '*', 'auto'],
          body: partBBody
        },
        layout: 'lightHorizontalLines',
        margin: [0, 0, 0, 15]
      });
    }
  }

  // ── Assemble Final Document ────────────────────────────────────────────
  const docDefinition = {
    info: {
      title: 'QP Analysis Report',
      author: 'QP Analyser Core Engine',
    },
    pageSize: 'A4',
    pageMargins: [40, 60, 40, 60],
    
    header: function(currentPage, pageCount) {
      return {
        text: `Page ${currentPage} of ${pageCount}`,
        alignment: 'right',
        margin: [0, 20, 40, 0],
        fontSize: 9,
        color: '#a0aec0'
      };
    },

    footer: function() {
      return {
        text: 'Generated by QP Analyzer Core Engine (Frontend)',
        alignment: 'center',
        fontSize: 9,
        color: '#a0aec0',
        margin: [0, 10, 0, 0]
      };
    },

    content: [
      { text: 'Question Paper Analysis Report', style: 'header' },
      { 
        text: `Modules Analyzed: ${Object.keys(data.syllabus).length || 'All'}  |  Total Questions: ${data.total_questions || 0}`,
        style: 'meta' 
      },
      
      { text: 'Top Analyzed Topics', style: 'sectionHeader' },
      {
        table: {
          headerRows: 1,
          widths: ['auto', '*', 'auto', 'auto'],
          body: topicsBody
        },
        layout: 'lightHorizontalLines'
      },

      { text: 'Advanced Predictions', style: 'sectionHeader', margin: [0, 20, 0, 10] },
      ...predictionsArray,
      
      { text: 'All Questions (Module-wise)', style: 'sectionHeader', margin: [0, 20, 0, 10], pageBreak: 'before' },
      ...moduleBlocks
    ],

    styles: {
      header: {
        fontSize: 22,
        bold: true,
        color: '#2b6cb0',
        margin: [0, 0, 0, 5]
      },
      meta: {
        fontSize: 10,
        color: '#718096',
        margin: [0, 0, 0, 20]
      },
      sectionHeader: {
        fontSize: 16,
        bold: true,
        color: '#2d3748',
        margin: [0, 15, 0, 10]
      },
      subheader: {
        fontSize: 14,
        bold: true,
        color: '#2d3748'
      },
      partHeader: {
        fontSize: 12,
        bold: true,
        color: '#4a5568'
      },
      tableHeader: {
        bold: true,
        fontSize: 11,
        color: '#4a5568',
        fillColor: '#f7fafc'
      }
    },
    defaultStyle: {
      fontSize: 10,
      color: '#333'
    }
  };

  pdfMake.createPdf(docDefinition).download('QP_Analysis_Report.pdf');
}
